set (SOURCE_LIST
	${CMAKE_CURRENT_SOURCE_DIR}/ClientTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/ClientTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/ServerTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/ServerTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/StorageTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/StorageTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/UdpTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/UdpTest.hpp
)
