set (SOURCE_LIST
	${CMAKE_CURRENT_SOURCE_DIR}/HandlerTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/HandlerTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/InternalTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/InternalTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/TcpTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/TcpTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/UdpTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/UdpTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/WorkerTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/WorkerTest.hpp
)
