set (SOURCE_LIST
	${CMAKE_CURRENT_SOURCE_DIR}/main.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/TestAggregator.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/TestAggregator.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Utils.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/Utils.hpp
)
