set (SOURCE_LIST
	${CMAKE_CURRENT_SOURCE_DIR}/ExpectedTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/ExpectedTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/FunctionalTraitTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/FunctionalTraitTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/TestAggregator.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/TestAggregator.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/UtilsTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/UtilsTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/VoidTypeTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/VoidTypeTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/main.cpp
)
