set (SOURCE_LIST
	${CMAKE_CURRENT_SOURCE_DIR}/Ipv4Test.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/Ipv4Test.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/LibraryTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/LibraryTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/TestAggregator.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/TestAggregator.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/main.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/UdpFunctionsTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/UdpFunctionsTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/UdpTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/UdpTest.hpp
)
