set (SOURCE_LIST
	${CMAKE_CURRENT_SOURCE_DIR}/Library.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/NamedPipe.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/Pipe.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/Process.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/TcpSocket.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/Thread.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/UdpSocket.cpp
)
