set (SOURCE_LIST
	${CMAKE_CURRENT_SOURCE_DIR}/Ipv4.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/Library.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/NetworkBase.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/TcpClient.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/TcpServer.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/UdpClient.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/UdpServer.cpp
)
