#ifndef FLAMEIDE_BSP_SERVER_BUILDTARGETOUTPUTPATHS_OUTPUTPATHITEMKIND_HPP
#define FLAMEIDE_BSP_SERVER_BUILDTARGETOUTPUTPATHS_OUTPUTPATHITEMKIND_HPP

namespace flame_ide
{namespace bsp
{namespace server
{

class OutputPathItemKind
{};

}}} // flame_ide::bsp::server

#endif // FLAMEIDE_BSP_SERVER_BUILDTARGETOUTPUTPATHS_OUTPUTPATHITEMKIND_HPP
