#ifndef FLAMEIDE_BSP_SERVER_BUILDTARGETOUTPUTPATHS_OUTPUTPATHSPARAMS_HPP
#define FLAMEIDE_BSP_SERVER_BUILDTARGETOUTPUTPATHS_OUTPUTPATHSPARAMS_HPP

namespace flame_ide
{namespace bsp
{namespace server
{

class OutputPathsParams
{};

}}} // flame_ide::bsp::server

#endif // FLAMEIDE_BSP_SERVER_BUILDTARGETOUTPUTPATHS_OUTPUTPATHSPARAMS_HPP
