#ifndef FLAMEIDE_BSP_SERVER_BUILDTARGETRESOURCES_RESOURCESRESULT_HPP
#define FLAMEIDE_BSP_SERVER_BUILDTARGETRESOURCES_RESOURCESRESULT_HPP

namespace flame_ide
{namespace bsp
{namespace server
{

class ResourcesResult
{};

}}} // flame_ide::bsp::server

#endif // FLAMEIDE_BSP_SERVER_BUILDTARGETRESOURCES_RESOURCESRESULT_HPP
