#ifndef FLAMEIDE_BSP_SERVER_BUILDTARGETRESOURCES_RESOURCESPARAMS_HPP
#define FLAMEIDE_BSP_SERVER_BUILDTARGETRESOURCES_RESOURCESPARAMS_HPP

namespace flame_ide
{namespace bsp
{namespace server
{

class ResourcesParams
{};

}}} // flame_ide::bsp::server

#endif // FLAMEIDE_BSP_SERVER_BUILDTARGETRESOURCES_RESOURCESPARAMS_HPP
