#!/bin/bash

build_type=release
Makefile="Makefile"

case "$1" in
"")
    make -j4 -f $Makefile BUILD_TYPE="$build_type"
    ;;

"clean")
    make -j4 -f $Makefile BUILD_TYPE="$build_type" clean
    ;;

"exec")
    make -j4 -f $Makefile BUILD_TYPE="$build_type" exec_test
    ;;
"leak")
#     valgrind --leak-check=full --show-leak-kinds=all .//release/bin/test_FlameIDE
    ;;
"mingw32")
    make -j4 -f $Makefile CC=i686-w64-mingw32-g++ BUILD_TYPE=$build_type
    ;;
"mingw64")
    make -j4 -f $Makefile CC=x86_64-w64-mingw32-g++ BUILD_TYPE=$build_type
    ;;
esac
exit

