#!/bin/bash

build_type=Release

case "$1" in
"")
    make -j4 -f Makefile BUILD="$build_type"
    ;;

"clean")
    make -j4 -f Makefile BUILD="$build_type" clean
    ;;

"exec")
    make -j4 -f Makefile BUILD="$build_type" exec_test
    ;;
"leak")
    valgrind --leak-check=full --show-leak-kinds=all ./Release/bin/test_FlameIDE
    ;;
"mingw32")
    make -j4 -f Makefile CC=i686-w64-mingw32-g++ BUILD=$TypeBuild
    ;;
"mingw64")
    make -j4 -f Makefile CC=x86_64-w64-mingw32-g++ BUILD=$TypeBuild
    ;;
esac
exit

