CONFIG :=true
NAME := FlameIDE
ifeq ($(BUILD_TYPE),)
    BUILD_TYPE := release
endif
ifeq ($(BUILD_PATH),)
    LOCAL_PATH := $(shell pwd)
    BUILD_PATH := $(LOCAL_PATH)/build/$(BUILD_TYPE)
endif

OBJ_PATH := $(BUILD_PATH)/obj
LIB_PATH := $(BUILD_PATH)/lib
BIN_PATH := $(BUILD_PATH)/bin
DEP_PATH := $(BUILD_PATH)/dep

TEST_PATH := $(BIN_PATH)/tests

ALL_PATHS := $(BUILD_PATH) \
    $(LIB_PATH) \
    $(BIN_PATH) \
    $(TEST_PATH) \
    $(DEP_PATH) \
    $(LOCAL_PATH)/build

CC := g++

override WARN_FLAGS := \
    -Wall \
    -Wextra \
    -Wconversion \
    -Winit-self \
    -Wunreachable-code \
    -Wformat=2 \
    -Wswitch-default \
    -Wtrigraphs \
    -Wstrict-overflow=4 \
    -Wfloat-equal \
    -Wundef \
    -Wshadow \
    -Wcast-qual \
    -Wcast-align \
    -Wwrite-strings \
    -Wlogical-op \
    -pedantic

override CXX_FLAGS := -std=c++14 -pipe ${WARN_FLAGS}
ifeq (BUILD_TYPE, release)
    CXX_FLAGS += -O2 -finline-functions -fno-rtti -Werror
endif
ifeq (BUILD_TYPE, debug)
    CXX_FLAGS += -pg -O0 -fno-inline-functions
endif
