ifndef (BUILD_PATH)
    LOCAL_PATH := $(shell pwd)
    ifndef (BUILD_TYPE)
        BUILD_TYPE := release
    endif
    BUILD_PATH := $(shell pwd)/build/$(BUILD_TYPE)
endif

OBJ_PATH := $(BUILD_PATH)/obj
LIB_PATH := $(BUILD_PATH)/lib
BIN_PATH := $(BUILD_PATH)/bin

TEST_PATH := $(BIN_PATH)/tests

ALL_PATHS := $(BUILD_PATH) \
             $(LIB_PATH) \
             $(BIN_PATH) \
             $(TEST_PATH)

MAKE_LIBS := ./src/Makefile
MAKE_TESTS := ./tests/Makefile

ifndef (CC)
    override CC := g++
endif

override CXXFLAGS :=
ifeq (BUILD_TYPE, relese)
    CXXFLAGS += 
endif
ifeq (BUILD_TYPE, debug)
    CXXFLAGS +=
endif
