set (HEADER_LIST
	${CMAKE_CURRENT_SOURCE_DIR}/Handler.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Ipv4.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/NetworkBase.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/TcpClient.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/TcpServer.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/UdpClient.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/UdpServer.hpp
)
