set (SOURCE_LIST
	${CMAKE_CURRENT_SOURCE_DIR}/MutexTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/MutexTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/SemaphoreTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/SemaphoreTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/TestAggregator.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/TestAggregator.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/ThreadTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/ThreadTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/main.cpp
)
