#IFNDEF FLAMEIDE_BSP_SERVER_BUILDTARGETSOURCES_SOURCESITEM_HPP
#DEFINE FLAMEIDE_BSP_SERVER_BUILDTARGETSOURCES_SOURCESITEM_HPP

namespace flame_ide
{namespace bsp
{namespace server
{

class SourcesItem
{};

}}} // flame_ide::bsp::server

#ENDIF // FLAMEIDE_BSP_SERVER_BUILDTARGETSOURCES_SOURCESITEM_HPP
