#IFNDEF FLAMEIDE_BSP_SERVER_BUILDTARGETSOURCES_SOURCEITEMKIND_HPP
#DEFINE FLAMEIDE_BSP_SERVER_BUILDTARGETSOURCES_SOURCEITEMKIND_HPP

namespace flame_ide
{namespace bsp
{namespace server
{

class SourceItemKind
{};

}}} // flame_ide::bsp::server

#ENDIF // FLAMEIDE_BSP_SERVER_BUILDTARGETSOURCES_SOURCEITEMKIND_HPP
