#IFNDEF FLAMEIDE_BSP_SERVER_BUILDTARGETSOURCES_SOURCEITEM_HPP
#DEFINE FLAMEIDE_BSP_SERVER_BUILDTARGETSOURCES_SOURCEITEM_HPP

namespace flame_ide
{namespace bsp
{namespace server
{

class SourceItem
{};

}}} // flame_ide::bsp::server

#ENDIF // FLAMEIDE_BSP_SERVER_BUILDTARGETSOURCES_SOURCEITEM_HPP
