#IFNDEF FLAMEIDE_BSP_SERVER_BUILDTARGETSOURCES_SOURCESPARAMS_HPP
#DEFINE FLAMEIDE_BSP_SERVER_BUILDTARGETSOURCES_SOURCESPARAMS_HPP

namespace flame_ide
{namespace bsp
{namespace server
{

class SourcesParams
{};

}}} // flame_ide::bsp::server

#ENDIF // FLAMEIDE_BSP_SERVER_BUILDTARGETSOURCES_SOURCESPARAMS_HPP
