set (HEADER_LIST
	${CMAKE_CURRENT_SOURCE_DIR}/Array.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/BaseValue.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/HugeNumber.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Object.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Pair.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Settings.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/SimpleTypeValues.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Stream.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/String.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Traits.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Types.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Value.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/ValueSpecializations.hpp
)
