#ifndef FLAMEIDE_BSP_CLIENT_ONBUILDPUBLISHDIAGNOSTICS_CODEDESCRIPTION_HPP
#define FLAMEIDE_BSP_CLIENT_ONBUILDPUBLISHDIAGNOSTICS_CODEDESCRIPTION_HPP

namespace flame_ide
{namespace bsp
{namespace client
{

class CodeDescription
{};

}}} // flame_ide::bsp::client

#endif // FLAMEIDE_BSP_CLIENT_ONBUILDPUBLISHDIAGNOSTICS_CODEDESCRIPTION_HPP
