#ifndef FLAMEIDE_BSP_CLIENT_ONBUILDPUBLISHDIAGNOSTICS_DIAGNOSTICDATAKIND_HPP
#define FLAMEIDE_BSP_CLIENT_ONBUILDPUBLISHDIAGNOSTICS_DIAGNOSTICDATAKIND_HPP

namespace flame_ide
{namespace bsp
{namespace client
{

class DiagnosticDataKind
{};

}}} // flame_ide::bsp::client

#endif // FLAMEIDE_BSP_CLIENT_ONBUILDPUBLISHDIAGNOSTICS_DIAGNOSTICDATAKIND_HPP
