#ifndef FLAMEIDE_BSP_CLIENT_ONBUILDPUBLISHDIAGNOSTICS_DIAGNOSTICSEVERITY_HPP
#define FLAMEIDE_BSP_CLIENT_ONBUILDPUBLISHDIAGNOSTICS_DIAGNOSTICSEVERITY_HPP

namespace flame_ide
{namespace bsp
{namespace client
{

class DiagnosticSeverity
{};

}}} // flame_ide::bsp::client

#endif // FLAMEIDE_BSP_CLIENT_ONBUILDPUBLISHDIAGNOSTICS_DIAGNOSTICSEVERITY_HPP
