#ifndef FLAMEIDE_BSP_CLIENT_ONBUILDPUBLISHDIAGNOSTICS_DIAGNOSTIC_HPP
#define FLAMEIDE_BSP_CLIENT_ONBUILDPUBLISHDIAGNOSTICS_DIAGNOSTIC_HPP

namespace flame_ide
{namespace bsp
{namespace client
{

class Diagnostic
{};

}}} // flame_ide::bsp::client

#endif // FLAMEIDE_BSP_CLIENT_ONBUILDPUBLISHDIAGNOSTICS_DIAGNOSTIC_HPP
