#ifndef FLAMEIDE_BSP_CLIENT_ONBUILDPUBLISHDIAGNOSTICS_DIAGNOSTICRELATEDINFORMATION_HPP
#define FLAMEIDE_BSP_CLIENT_ONBUILDPUBLISHDIAGNOSTICS_DIAGNOSTICRELATEDINFORMATION_HPP

namespace flame_ide
{namespace bsp
{namespace client
{

class DiagnosticRelatedInformation
{};

}}} // flame_ide::bsp::client

#endif // FLAMEIDE_BSP_CLIENT_ONBUILDPUBLISHDIAGNOSTICS_DIAGNOSTICRELATEDINFORMATION_HPP
