#ifndef FLAMEIDE_BSP_CLIENT_ONBUILDPUBLISHDIAGNOSTICS_DIAGNOSTICTAG_HPP
#define FLAMEIDE_BSP_CLIENT_ONBUILDPUBLISHDIAGNOSTICS_DIAGNOSTICTAG_HPP

namespace flame_ide
{namespace bsp
{namespace client
{

class DiagnosticTag
{};

}}} // flame_ide::bsp::client

#endif // FLAMEIDE_BSP_CLIENT_ONBUILDPUBLISHDIAGNOSTICS_DIAGNOSTICTAG_HPP
