#ifndef FLAMEIDE_BSP_CLIENT_ONBUILDPUBLISHDIAGNOSTICS_LOCATION_HPP
#define FLAMEIDE_BSP_CLIENT_ONBUILDPUBLISHDIAGNOSTICS_LOCATION_HPP

namespace flame_ide
{namespace bsp
{namespace client
{

class Location
{};

}}} // flame_ide::bsp::client

#endif // FLAMEIDE_BSP_CLIENT_ONBUILDPUBLISHDIAGNOSTICS_LOCATION_HPP
