#ifndef FLAMEIDE_BSP_CLIENT_ONBUILDPUBLISHDIAGNOSTICS_PUBLISHDIAGNOSTICSPARAMS_HPP
#define FLAMEIDE_BSP_CLIENT_ONBUILDPUBLISHDIAGNOSTICS_PUBLISHDIAGNOSTICSPARAMS_HPP

namespace flame_ide
{namespace bsp
{namespace client
{

class PublishDiagnosticsParams
{};

}}} // flame_ide::bsp::client

#endif // FLAMEIDE_BSP_CLIENT_ONBUILDPUBLISHDIAGNOSTICS_PUBLISHDIAGNOSTICSPARAMS_HPP
