#ifndef FLAMEIDE_BSP_CLIENT_ONBUILDSHOWMESSAGE_SHOWMESSAGEPARAMS_HPP
#define FLAMEIDE_BSP_CLIENT_ONBUILDSHOWMESSAGE_SHOWMESSAGEPARAMS_HPP

namespace flame_ide
{namespace bsp
{namespace client
{

class ShowMessageParams
{};

}}} // flame_ide::bsp::client

#endif // FLAMEIDE_BSP_CLIENT_ONBUILDSHOWMESSAGE_SHOWMESSAGEPARAMS_HPP
