set (SOURCE_LIST
	${CMAKE_CURRENT_SOURCE_DIR}/InitializeArgs.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/Object.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/Pkcs11.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/Session.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/Slot.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/Token.cpp
)
