#ifndef FLAMEIDE_TEMPLATES_ALLOCATOR_STATICALLOCATOR_HPP
#define FLAMEIDE_TEMPLATES_ALLOCATOR_STATICALLOCATOR_HPP

namespace flame_ide
{

} // namespace flame_ide

#endif // FLAMEIDE_TEMPLATES_ALLOCATOR_STATICALLOCATOR_HPP
