#ifndef FLAMEIDE_BSP_SERVER_BUILDTARGETDEPENDENCYSOURCES_DEPENDENCYSOURCESITEM_HPP
#define FLAMEIDE_BSP_SERVER_BUILDTARGETDEPENDENCYSOURCES_DEPENDENCYSOURCESITEM_HPP

namespace flame_ide
{namespace bsp
{namespace server
{

class DependencySourcesItem
{};

}}} // flame_ide::bsp::server

#endif // FLAMEIDE_BSP_SERVER_BUILDTARGETDEPENDENCYSOURCES_DEPENDENCYSOURCESITEM_HPP
