#ifndef FLAMEIDE_BSP_SERVER_BUILDTARGETDEPENDENCYSOURCES_DEPENDENCYSOURCESRESULT_HPP
#define FLAMEIDE_BSP_SERVER_BUILDTARGETDEPENDENCYSOURCES_DEPENDENCYSOURCESRESULT_HPP

namespace flame_ide
{namespace bsp
{namespace server
{

class DependencySourcesResult
{};

}}} // flame_ide::bsp::server

#endif // FLAMEIDE_BSP_SERVER_BUILDTARGETDEPENDENCYSOURCES_DEPENDENCYSOURCESRESULT_HPP
