#ifndef FLAMEIDE_BSP_SERVER_BUILDTARGETDEPENDENCYSOURCES_DEPENDENCYSOURCESPARAMS_HPP
#define FLAMEIDE_BSP_SERVER_BUILDTARGETDEPENDENCYSOURCES_DEPENDENCYSOURCESPARAMS_HPP

namespace flame_ide
{namespace bsp
{namespace server
{

class DependencySourcesParams
{};

}}} // flame_ide::bsp::server

#endif // FLAMEIDE_BSP_SERVER_BUILDTARGETDEPENDENCYSOURCES_DEPENDENCYSOURCESPARAMS_HPP
