set (HEADER_LIST
	${CMAKE_CURRENT_SOURCE_DIR}/InternetCode.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/SystemCode0.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/SystemCode1.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/SystemCode2.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/SystemCode3.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/SystemCode4.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/SystemCode5.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/SystemCode6.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/SystemCode7.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/SystemCode8.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/SystemCode9.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/WinHttpCode.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/WsaError.hpp
)
