set (SOURCE_LIST
	${CMAKE_CURRENT_SOURCE_DIR}/InternetCode.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/SystemCode0.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/SystemCode1.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/SystemCode2.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/SystemCode3.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/SystemCode4.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/SystemCode5.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/SystemCode6.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/SystemCode7.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/SystemCode8.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/SystemCode9.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/WinHttpCode.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/WsaError.cpp
)
