#ifndef FLAMEIDE_COMMON_MACROSES_BYTEORDER_HPP
#define FLAMEIDE_COMMON_MACROSES_BYTEORDER_HPP

#include <FlameIDE/Common/Macroses/DetectOs.hpp>

#if FLAMEIDE_OS_CURRENT < FLAMEIDE_OS_WINDOWS
#	define FLAMEIDE_ORDER_LITTLE_ENDIAN          __ORDER_LITTLE_ENDIAN__
#	define FLAMEIDE_ORDER_BIG_ENDIAN             __ORDER_BIG_ENDIAN__
#	define FLAMEIDE_ORDER_PDP_ENDIAN             __ORDER_PDP_ENDIAN__
#	define FLAMEIDE_ORDER_CURRENT                __BYTE_ORDER__
#endif // FLAMEIDE_OS_CURRENT != FLAMEIDE_OS_WINDOWS

#if FLAMEIDE_OS_CURRENT == FLAMEIDE_OS_WINDOWS
#	define FLAMEIDE_ORDER_LITTLE_ENDIAN          0
#	define FLAMEIDE_ORDER_BIG_ENDIAN             1
#	define FLAMEIDE_ORDER_PDP_ENDIAN             2
#	define FLAMEIDE_ORDER_CURRENT                FLAMEIDE_ORDER_LITTLE_ENDIAN
#endif // FLAMEIDE_OS_CURRENT == FLAMEIDE_OS_WINDOWS


#endif // FLAMEIDE_COMMON_MACROSES_BYTEORDER_HPP
