cmake_minimum_required(VERSION 3.14)

# Udp

set(UDP_MESSAGE_SIZE_KB 32)

set(UDP_SERVERS 8)
set(UDP_SERVER_INPUT_QUEUE_SIZE  32)
set(UDP_SERVER_OUTPUT_QUEUE_SIZE 32)

set(UDP_CLIENTS 16)
set(UDP_CLIENT_INPUT_QUEUE_SIZE  32)
set(UDP_CLIENT_OUTPUT_QUEUE_SIZE 32)

# Tcp

set(TCP_SERVERS 8)
set(TCP_SERVER_INPUT_BUFFER_KB  64)
set(TCP_SERVER_OUTPUT_BUFFER_KB 64)

set(TCP_CLIENTS 16)
set(TCP_CLIENT_INPUT_BUFFER_KB  64)
set(TCP_CLIENT_OUTPUT_BUFFER_KB 64)

# Common

set(NUMBER_OF_WORKERS 2)

# Add defines

set(HANDLER_NETWORK_DEFINES
	"HANDLER_NETWORK_UDP_SERVERS=${UDP_SERVERS}"
	"HANDLER_NETWORK_UDP_CLIENTS=${UDP_CLIENTS}"
	"HANDLER_NETWORK_UDP_MESSAGE_SIZE_KB=${UDP_MESSAGE_SIZE_KB}"
	"HANDLER_NETWORK_UDP_SERVER_INPUT_QUEUE_SIZE=${UDP_SERVER_INPUT_QUEUE_SIZE}"
	"HANDLER_NETWORK_UDP_SERVER_OUTPUT_QUEUE_SIZE=${UDP_SERVER_OUTPUT_QUEUE_SIZE}"
	"HANDLER_NETWORK_UDP_CLIENT_INPUT_QUEUE_SIZE=${UDP_CLIENT_INPUT_QUEUE_SIZE}"
	"HANDLER_NETWORK_UDP_CLIENT_OUTPUT_QUEUE_SIZE=${UDP_CLIENT_OUTPUT_QUEUE_SIZE}"

	"HANDLER_NETWORK_TCP_SERVERS=${TCP_SERVERS}"
	"HANDLER_NETWORK_TCP_CLIENTS=${TCP_CLIENTS}"
	"HANDLER_NETWORK_TCP_SERVER_INPUT_BUFFER_KB=${TCP_SERVER_INPUT_BUFFER_KB}"
	"HANDLER_NETWORK_TCP_SERVER_OUTPUT_BUFFER_KB=${TCP_SERVER_OUTPUT_BUFFER_KB}"
	"HANDLER_NETWORK_TCP_CLIENT_INPUT_BUFFER_KB=${TCP_CLIENT_INPUT_BUFFER_KB}"
	"HANDLER_NETWORK_TCP_CLIENT_OUTPUT_BUFFER_KB=${TCP_CLIENT_OUTPUT_BUFFER_KB}"

	"HANDLER_NETWORK_NUMBER_OF_WORKERS=${NUMBER_OF_WORKERS}"
)
