set (HEADER_LIST
	${CMAKE_CURRENT_SOURCE_DIR}/Functions.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Internal.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Tcp.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/TcpClient.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/TcpConfig.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/TcpServer.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/TcpTypes.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Udp.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/UdpClient.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/UdpConfig.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/UdpServer.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/UdpTypes.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Worker.hpp
)
