set (HEADER_LIST
	${CMAKE_CURRENT_SOURCE_DIR}/Functions.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Internal.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Tcp.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Udp.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Worker.hpp
)
