set (SOURCE_LIST
	${CMAKE_CURRENT_SOURCE_DIR}/Handler.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/Internal.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/Notificator.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/ServerHandle.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/SessionHandle.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/Tcp.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/Udp.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/WorkerBase.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/Workers.cpp
)
