set (SOURCE_LIST
	${CMAKE_CURRENT_SOURCE_DIR}/CommunicationHandle.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/Handler.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/Internal.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/ServerHandle.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/Worker.cpp
)
