#ifndef FLAMEIDE_BSP_CLIENT_ONBUILDTASKPROGRESS_TASKPROGRESSDATAKIND_HPP
#define FLAMEIDE_BSP_CLIENT_ONBUILDTASKPROGRESS_TASKPROGRESSDATAKIND_HPP

namespace flame_ide
{namespace bsp
{namespace client
{

class TaskProgressDataKind
{};

}}} // flame_ide::bsp::client

#endif // FLAMEIDE_BSP_CLIENT_ONBUILDTASKPROGRESS_TASKPROGRESSDATAKIND_HPP
