#ifndef FLAMEIDE_BSP_CLIENT_ONBUILDTASKPROGRESS_TASKPROGRESSDATA_HPP
#define FLAMEIDE_BSP_CLIENT_ONBUILDTASKPROGRESS_TASKPROGRESSDATA_HPP

namespace flame_ide
{namespace bsp
{namespace client
{

class TaskProgressData
{};

}}} // flame_ide::bsp::client

#endif // FLAMEIDE_BSP_CLIENT_ONBUILDTASKPROGRESS_TASKPROGRESSDATA_HPP
