#ifndef TEXTSTYLE_H
#define TEXTSTYLE_H

#if defined(__unix__)
#define TEXT_STYLE_PLATFORM(text) text
#else
#define TEXT_STYLE_PLATFORM(text) ""
#endif

#define TEXT_STYLE_NULL              TEXT_STYLE_PLATFORM("\033[0m") // сброс
#define TEXT_STYLE_BOLD              TEXT_STYLE_PLATFORM("\033[1m")
#define TEXT_STYLE_MIDDLE            TEXT_STYLE_PLATFORM("\033[2m")
#define TEXT_STYLE_LIGHT             TEXT_STYLE_PLATFORM("\033[3m")
#define TEXT_STYLE_UNDERLINE         TEXT_STYLE_PLATFORM("\033[4m")
#define TEXT_STYLE_BINK              TEXT_STYLE_PLATFORM("\033[5m")
#define TEXT_STYLE_INVERT            TEXT_STYLE_PLATFORM("\033[7m")
#define TEXT_STYLE_INVISIBLE         TEXT_STYLE_PLATFORM("\033[8m")
#define TEXT_STYLE_BLACK             TEXT_STYLE_PLATFORM("\033[30m")
#define TEXT_STYLE_RED               TEXT_STYLE_PLATFORM("\033[31m")
#define TEXT_STYLE_GREEN             TEXT_STYLE_PLATFORM("\033[32m")
#define TEXT_STYLE_YELLOW            TEXT_STYLE_PLATFORM("\033[33m")
#define TEXT_STYLE_BLUE              TEXT_STYLE_PLATFORM("\033[34m")
#define TEXT_STYLE_VIOLET            TEXT_STYLE_PLATFORM("\033[35m")
#define TEXT_STYLE_CYAN              TEXT_STYLE_PLATFORM("\033[36m")
#define TEXT_STYLE_WHITE             TEXT_STYLE_PLATFORM("\033[37m")
#define TEXT_STYLE_BLACK_BACKGROUND  TEXT_STYLE_PLATFORM("\033[40m")
#define TEXT_STYLE_RED_BACKGROUND    TEXT_STYLE_PLATFORM("\033[41m")
#define TEXT_STYLE_GREEN_BACKGROUND  TEXT_STYLE_PLATFORM("\033[42m")
#define TEXT_STYLE_YELLOW_BACKGROUND TEXT_STYLE_PLATFORM("\033[43m")
#define TEXT_STYLE_BLUE_BACKGROUND   TEXT_STYLE_PLATFORM("\033[44m")
#define TEXT_STYLE_VIOLET_BACKGROUND TEXT_STYLE_PLATFORM("\033[45m")
#define TEXT_STYLE_CYAN_BACKGROUND   TEXT_STYLE_PLATFORM("\033[46m")
#define TEXT_STYLE_WHITE_BACKGROUND  TEXT_STYLE_PLATFORM("\033[47m")

//#undef TEXT_STYLE_PLATFORM

#endif // TEXTSTYLE_H
