#ifndef FLAMEIDE_BSP_SERVER_BUILDTARGETINVERSESOURCES_INVERSESOURCESPARAMS_HPP
#define FLAMEIDE_BSP_SERVER_BUILDTARGETINVERSESOURCES_INVERSESOURCESPARAMS_HPP

namespace flame_ide
{namespace bsp
{namespace server
{

class InverseSourcesParams
{};

}}} // flame_ide::bsp::server

#endif // FLAMEIDE_BSP_SERVER_BUILDTARGETINVERSESOURCES_INVERSESOURCESPARAMS_HPP
