#ifndef FLAMEIDE_BSP_SERVER_BUILDTARGETINVERSESOURCES_INVERSESOURCESRESULT_HPP
#define FLAMEIDE_BSP_SERVER_BUILDTARGETINVERSESOURCES_INVERSESOURCESRESULT_HPP

namespace flame_ide
{namespace bsp
{namespace server
{

class InverseSourcesResult
{};

}}} // flame_ide::bsp::server

#endif // FLAMEIDE_BSP_SERVER_BUILDTARGETINVERSESOURCES_INVERSESOURCESRESULT_HPP
