#ifndef FLAMEIDE_BSP_SERVER_BUILDTARGETINVERSESOURCES_TEXTDOCUMENTIDENTIFIER_HPP
#define FLAMEIDE_BSP_SERVER_BUILDTARGETINVERSESOURCES_TEXTDOCUMENTIDENTIFIER_HPP

namespace flame_ide
{namespace bsp
{namespace server
{

class TextDocumentIdentifier
{};

}}} // flame_ide::bsp::server

#endif // FLAMEIDE_BSP_SERVER_BUILDTARGETINVERSESOURCES_TEXTDOCUMENTIDENTIFIER_HPP
