set (HEADER_LIST
	${CMAKE_CURRENT_SOURCE_DIR}/Byte.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Constants.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/FunctorBase.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Macros.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/PrimitiveTypes.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/ReferenceWrapper.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Traits.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Utils.hpp
)
