set (HEADER_LIST
	${CMAKE_CURRENT_SOURCE_DIR}/Byte.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Constants.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Macroses.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/OsTypes.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/PrimitiveTypes.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Traits.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Utils.hpp
)
