#ifndef FLAMEIDE_COMMON_MACROSES_HPP
#define FLAMEIDE_COMMON_MACROSES_HPP

#ifdef _WIN32
#	define FLAMEIDE_ORDER_LITTLE_ENDIAN 0
#	define FLAMEIDE_ORDER_BIG_ENDIAN    1
#	define FLAMEIDE_ORDER_PDP_ENDIAN    2
#	define FLAMEIDE_ORDER_CURRENT       FLAMEIDE_ORDER_LITTLE_ENDIAN
#else
#	define FLAMEIDE_ORDER_LITTLE_ENDIAN __ORDER_LITTLE_ENDIAN__
#	define FLAMEIDE_ORDER_BIG_ENDIAN    __ORDER_BIG_ENDIAN__
#	define FLAMEIDE_ORDER_PDP_ENDIAN    __ORDER_PDP_ENDIAN__
#	define FLAMEIDE_ORDER_CURRENT       __BYTE_ORDER__
#endif

#endif // FLAMEIDE_COMMON_MACROSES_HPP
