#ifndef FLAMEIDE_BSP_SERVER_WORKSPACEBUILDTARGETS_WORKSPACEBUILDTARGETSRESULT_HPP
#define FLAMEIDE_BSP_SERVER_WORKSPACEBUILDTARGETS_WORKSPACEBUILDTARGETSRESULT_HPP

namespace flame_ide
{namespace bsp
{namespace server
{

class WorkspaceBuildTargetsResult
{};

}}} // flame_ide::bsp::server

#endif // FLAMEIDE_BSP_SERVER_WORKSPACEBUILDTARGETS_WORKSPACEBUILDTARGETSRESULT_HPP
