#ifndef FLAMEIDE_BSP_SERVER_BUILDTARGETCLEANCACHE_CLEANCACHERESULT_HPP
#define FLAMEIDE_BSP_SERVER_BUILDTARGETCLEANCACHE_CLEANCACHERESULT_HPP

namespace flame_ide
{namespace bsp
{namespace server
{

class CleanCacheResult
{};

}}} // flame_ide::bsp::server

#endif // FLAMEIDE_BSP_SERVER_BUILDTARGETCLEANCACHE_CLEANCACHERESULT_HPP
