set (SOURCE_LIST
	${CMAKE_CURRENT_SOURCE_DIR}/HandlerTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/HandlerTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Ipv4Test.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/Ipv4Test.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/TcpFunctionsTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/TcpFunctionsTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/TcpTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/TcpTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/UdpFunctionsTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/UdpFunctionsTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/UdpTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/UdpTest.hpp
)
