set (HEADER_LIST
	${CMAKE_CURRENT_SOURCE_DIR}/Mutex.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Semaphore.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Spin.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Thread.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Utils.hpp
)
