set (HEADER_LIST
	${CMAKE_CURRENT_SOURCE_DIR}/Client.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Config.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Endpoint.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/InternalData.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Server.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Types.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Udp.hpp
)
