set (HEADER_LIST
	${CMAKE_CURRENT_SOURCE_DIR}/ActualData.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Client.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Config.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/ContainerTypes.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Endpoint.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Message.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Server.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Storage.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/TypeMapping.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Types.hpp
)
