set (HEADER_LIST
	${CMAKE_CURRENT_SOURCE_DIR}/Array.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Number.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Object.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/String.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Value.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Whitespace.hpp
)
