set (SOURCE_LIST
	${CMAKE_CURRENT_SOURCE_DIR}/Array.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/Number.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/Object.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/String.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/Value.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/Whitespace.cpp
)
