#ifndef FLAMEIDE_BSP_CLIENT_ONBUILDTASKSTART_TASKSTARTDATAKIND_HPP
#define FLAMEIDE_BSP_CLIENT_ONBUILDTASKSTART_TASKSTARTDATAKIND_HPP

namespace flame_ide
{namespace bsp
{namespace client
{

class TaskStartDataKind
{};

}}} // flame_ide::bsp::client

#endif // FLAMEIDE_BSP_CLIENT_ONBUILDTASKSTART_TASKSTARTDATAKIND_HPP
