#ifndef FLAMEIDE_BSP_CLIENT_ONBUILDLOGMESSAGE_LOGMESSAGEPARAMS_HPP
#define FLAMEIDE_BSP_CLIENT_ONBUILDLOGMESSAGE_LOGMESSAGEPARAMS_HPP

namespace flame_ide
{namespace bsp
{namespace client
{

class LogMessageParams
{};

}}} // flame_ide::bsp::client

#endif // FLAMEIDE_BSP_CLIENT_ONBUILDLOGMESSAGE_LOGMESSAGEPARAMS_HPP
