#ifndef FLAMEIDE_BSP_CLIENT_ONBUILDTASKFINISH_TASKFINISHDATA_HPP
#define FLAMEIDE_BSP_CLIENT_ONBUILDTASKFINISH_TASKFINISHDATA_HPP

namespace flame_ide
{namespace bsp
{namespace client
{

class TaskFinishData
{};

}}} // flame_ide::bsp::client

#endif // FLAMEIDE_BSP_CLIENT_ONBUILDTASKFINISH_TASKFINISHDATA_HPP
