#ifndef FLAMEIDE_BSP_CLIENT_ONBUILDTASKFINISH_TASKFINISHDATAKIND_HPP
#define FLAMEIDE_BSP_CLIENT_ONBUILDTASKFINISH_TASKFINISHDATAKIND_HPP

namespace flame_ide
{namespace bsp
{namespace client
{

class TaskFinishDataKind
{};

}}} // flame_ide::bsp::client

#endif // FLAMEIDE_BSP_CLIENT_ONBUILDTASKFINISH_TASKFINISHDATAKIND_HPP
