#ifndef FLAMEIDE_BSP_CLIENT_ONBUILDTASKFINISH_TASKFINISHPARAMS_HPP
#define FLAMEIDE_BSP_CLIENT_ONBUILDTASKFINISH_TASKFINISHPARAMS_HPP

namespace flame_ide
{namespace bsp
{namespace client
{

class TaskFinishParams
{};

}}} // flame_ide::bsp::client

#endif // FLAMEIDE_BSP_CLIENT_ONBUILDTASKFINISH_TASKFINISHPARAMS_HPP
