#ifndef FLAMEIDE_BSP_CLIENT_ONBUILDTASKFINISH_TESTFINISHDATA_HPP
#define FLAMEIDE_BSP_CLIENT_ONBUILDTASKFINISH_TESTFINISHDATA_HPP

namespace flame_ide
{namespace bsp
{namespace client
{

class TestFinishData
{};

}}} // flame_ide::bsp::client

#endif // FLAMEIDE_BSP_CLIENT_ONBUILDTASKFINISH_TESTFINISHDATA_HPP
