#ifndef FLAMEIDE_BSP_CLIENT_ONBUILDTASKFINISH_TESTFINISHDATAKIND_HPP
#define FLAMEIDE_BSP_CLIENT_ONBUILDTASKFINISH_TESTFINISHDATAKIND_HPP

namespace flame_ide
{namespace bsp
{namespace client
{

class TestFinishDataKind
{};

}}} // flame_ide::bsp::client

#endif // FLAMEIDE_BSP_CLIENT_ONBUILDTASKFINISH_TESTFINISHDATAKIND_HPP
