#ifndef FLAMEIDE_BSP_SERVER_DEBUGSESSIONSTART_DEBUGSESSIONPARAMSDATAKIND_HPP
#define FLAMEIDE_BSP_SERVER_DEBUGSESSIONSTART_DEBUGSESSIONPARAMSDATAKIND_HPP

namespace flame_ide
{namespace bsp
{namespace server
{

class DebugSessionParamsDataKind
{};

}}} // flame_ide::bsp::server

#endif // FLAMEIDE_BSP_SERVER_DEBUGSESSIONSTART_DEBUGSESSIONPARAMSDATAKIND_HPP
