#ifndef FLAMEIDE_BSP_SERVER_DEBUGSESSIONSTART_DEBUGSESSIONPARAMSDATA_HPP
#define FLAMEIDE_BSP_SERVER_DEBUGSESSIONSTART_DEBUGSESSIONPARAMSDATA_HPP

namespace flame_ide
{namespace bsp
{namespace server
{

class DebugSessionParamsData
{};

}}} // flame_ide::bsp::server

#endif // FLAMEIDE_BSP_SERVER_DEBUGSESSIONSTART_DEBUGSESSIONPARAMSDATA_HPP
