#ifndef FLAMEIDE_BSP_SERVER_DEBUGSESSIONSTART_DEBUGSESSIONPARAMS_HPP
#define FLAMEIDE_BSP_SERVER_DEBUGSESSIONSTART_DEBUGSESSIONPARAMS_HPP

namespace flame_ide
{namespace bsp
{namespace server
{

class DebugSessionParams
{};

}}} // flame_ide::bsp::server

#endif // FLAMEIDE_BSP_SERVER_DEBUGSESSIONSTART_DEBUGSESSIONPARAMS_HPP
