set (HEADER_LIST
	${CMAKE_CURRENT_SOURCE_DIR}/Constants.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Ipv4.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Library.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/NetworkBase.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Types.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/UdpClient.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/UdpServer.hpp
)
