set (HEADER_LIST
	${CMAKE_CURRENT_SOURCE_DIR}/Constants.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Library.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/NamedPipe.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Pipe.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Process.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/TcpSocket.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Thread.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Types.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/UdpSocket.hpp
)
