set(FLAME_PLATFORM Posix)

find_library(PTHREAD_LIBRARY pthread)
set(FLAME_LIBRARIES ${PTHREAD_LIBRARY})

include(CheckIncludeFile)
if(FLAMEIDE_ENABLE_ASYNC)
	set(CHECK_AIO_H)
	check_include_file("aio.h" CHECK_AIO_H)
	if(NOT CHECK_AIO_H)
		message(FATAL_ERROR "Not found 'aio.h'")
	else()
		add_definitions("-DFLAMEIDE_ENABLE_ASYNC=1")
	endif()
endif()
