set (HEADER_LIST
	${CMAKE_CURRENT_SOURCE_DIR}/BuildTarget.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/BuildTargetCapabilities.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/BuildTargetData.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/BuildTargetDataKind.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/BuildTargetTag.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/EnvironmentVariables.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Identifier.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/LanguageId.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/OriginId.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/StatusCode.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/TaskId.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/Uri.hpp
)
