set (SOURCE_LIST
	${CMAKE_CURRENT_SOURCE_DIR}/AllocatorTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/AllocatorTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/ArrayTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/ArrayTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/AsIntegralTypeTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/AsIntegralTypeTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/BinaryTreesTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/BinaryTreesTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/BitsTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/BitsTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/BuilderTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/BuilderTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/ByteOrderTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/ByteOrderTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/CircularArrayTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/CircularArrayTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/CircularIteratorTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/CircularIteratorTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/CircularVectorTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/CircularVectorTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/ExpectedTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/ExpectedTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/FutureTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/FutureTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/HybridVectorTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/HybridVectorTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/IntegerIteratorTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/IntegerIteratorTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/ListTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/ListTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/ObjectTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/ObjectTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/SerializationTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/SerializationTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/SharedPointerTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/SharedPointerTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/StringConvertionsTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/StringConvertionsTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/StringTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/StringTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/TestAggregator.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/TestAggregator.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/TestClass.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/TestClass.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/TupleTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/TupleTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/UniquePoiterTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/UniquePoiterTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/VariantTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/VariantTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/VectorTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/VectorTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/WideIntTest.cpp
	${CMAKE_CURRENT_SOURCE_DIR}/WideIntTest.hpp
	${CMAKE_CURRENT_SOURCE_DIR}/main.cpp
)
