#ifndef FLAMEIDE_BSP_SERVER_BUILDTARGETTEST_TESTPARAMSDATAKIND_HPP
#define FLAMEIDE_BSP_SERVER_BUILDTARGETTEST_TESTPARAMSDATAKIND_HPP

namespace flame_ide
{namespace bsp
{namespace server
{

class TestParamsDataKind
{};

}}} // flame_ide::bsp::server

#endif // FLAMEIDE_BSP_SERVER_BUILDTARGETTEST_TESTPARAMSDATAKIND_HPP
