#ifndef FLAMEIDE_BSP_SERVER_BUILDINITIALIZE_BUILDCLIENTCAPABILITIES_HPP
#define FLAMEIDE_BSP_SERVER_BUILDINITIALIZE_BUILDCLIENTCAPABILITIES_HPP

namespace flame_ide
{namespace bsp
{namespace server
{

class BuildClientCapabilities
{};

}}} // flame_ide::bsp::server

#endif // FLAMEIDE_BSP_SERVER_BUILDINITIALIZE_BUILDCLIENTCAPABILITIES_HPP
