#ifndef FLAMEIDE_BSP_SERVER_BUILDINITIALIZE_INITIALIZEBUILDPARAMS_HPP
#define FLAMEIDE_BSP_SERVER_BUILDINITIALIZE_INITIALIZEBUILDPARAMS_HPP

namespace flame_ide
{namespace bsp
{namespace server
{

class InitializeBuildParams
{};

}}} // flame_ide::bsp::server

#endif // FLAMEIDE_BSP_SERVER_BUILDINITIALIZE_INITIALIZEBUILDPARAMS_HPP
