#ifndef FLAMEIDE_BSP_SERVER_BUILDINITIALIZE_INITIALIZEBUILDPARAMSDATAKIND_HPP
#define FLAMEIDE_BSP_SERVER_BUILDINITIALIZE_INITIALIZEBUILDPARAMSDATAKIND_HPP

namespace flame_ide
{namespace bsp
{namespace server
{

class InitializeBuildParamsDataKind
{};

}}} // flame_ide::bsp::server

#endif // FLAMEIDE_BSP_SERVER_BUILDINITIALIZE_INITIALIZEBUILDPARAMSDATAKIND_HPP
