#ifndef FLAMEIDE_BSP_SERVER_BUILDINITIALIZE_INITIALIZEBUILDRESULTDATAKIND_HPP
#define FLAMEIDE_BSP_SERVER_BUILDINITIALIZE_INITIALIZEBUILDRESULTDATAKIND_HPP

namespace flame_ide
{namespace bsp
{namespace server
{

class InitializeBuildResultDataKind
{};

}}} // flame_ide::bsp::server

#endif // FLAMEIDE_BSP_SERVER_BUILDINITIALIZE_INITIALIZEBUILDRESULTDATAKIND_HPP
