#ifndef FLAMEIDE_BSP_SERVER_BUILDINITIALIZE_INITIALIZEBUILDRESULTDATA_HPP
#define FLAMEIDE_BSP_SERVER_BUILDINITIALIZE_INITIALIZEBUILDRESULTDATA_HPP

namespace flame_ide
{namespace bsp
{namespace server
{

class InitializeBuildResultData
{};

}}} // flame_ide::bsp::server

#endif // FLAMEIDE_BSP_SERVER_BUILDINITIALIZE_INITIALIZEBUILDRESULTDATA_HPP
