#ifndef FLAMEIDE_BSP_CLIENT_ONBUILDTARGETDIDCHANGE_BUILDTARGETEVENTKIND_HPP
#define FLAMEIDE_BSP_CLIENT_ONBUILDTARGETDIDCHANGE_BUILDTARGETEVENTKIND_HPP

namespace flame_ide
{namespace bsp
{namespace client
{

class BuildTargetEventKind
{};

}}} // flame_ide::bsp::client

#endif // FLAMEIDE_BSP_CLIENT_ONBUILDTARGETDIDCHANGE_BUILDTARGETEVENTKIND_HPP
