#ifndef FLAMEIDE_BSP_CLIENT_ONBUILDTARGETDIDCHANGE_BUILDTARGETEVENTDATA_HPP
#define FLAMEIDE_BSP_CLIENT_ONBUILDTARGETDIDCHANGE_BUILDTARGETEVENTDATA_HPP

namespace flame_ide
{namespace bsp
{namespace client
{

class BuildTargetEventData
{};

}}} // flame_ide::bsp::client

#endif // FLAMEIDE_BSP_CLIENT_ONBUILDTARGETDIDCHANGE_BUILDTARGETEVENTDATA_HPP
