#ifndef FLAMEIDE_BSP_CLIENT_ONBUILDTARGETDIDCHANGE_DIDCHANGEBUILDTARGET_HPP
#define FLAMEIDE_BSP_CLIENT_ONBUILDTARGETDIDCHANGE_DIDCHANGEBUILDTARGET_HPP

namespace flame_ide
{namespace bsp
{namespace client
{

class DidChangeBuildTarget
{};

}}} // flame_ide::bsp::client

#endif // FLAMEIDE_BSP_CLIENT_ONBUILDTARGETDIDCHANGE__HPP
