name: 'Build libraries'

on:
  push:
    branches:
      - '**'
    paths:
      - '.github/workflows/**'
      - 'cmake/**'
      - 'include/**'
      - 'src/**'
      - 'tests/**'
      - '**/CMakeLists.txt'
      - '**/*.pro'
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/**'
      - 'cmake/**'
      - 'include/**'
      - 'src/**'
      - 'tests/**'
      - '**/CMakeLists.txt'
      - '**/*.pro'

defaults:
  run:
    shell: bash

jobs:
  build-libraries:
    name: 'Build libraries'

    strategy:
      matrix:
        system:
          - windows-latest
          - ubuntu-latest
        config:
          - Debug
          - Release
        include:
          - system: windows-latest
            compiler: [{ cc: cl, cpp: cl }]
          - system: ubuntu-latest
            compiler: [{ cc: gcc-13, cpp: g++-13 }]
          - system: ubuntu-latest
            compiler: [{ cc: clang-14, cpp: clang++-14 }]
      fail-fast: false

    runs-on: ${{ matrix.system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Ninja
        uses: imesense/gha-setup-ninja@v0.1.1

      - name: Configure project
        run: |
          cmake \
            -S . \
            -B build \
            -G "Ninja" \
            -DCMAKE_C_COMPILER=${{ matrix.compiler.cc }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.compiler.cpp }} \
            -DFLAME_CONAN_SUPPORT=OFF \
            -DCMAKE_BUILD_TYPE=${{ matrix.config }}

      - name: Build project
        run: |
          cmake \
            --build build \
            --config ${{ matrix.config }}

      - name: Run tests
        run: |
          cmake \
            --build build \
            --target test
