#ifndef FLAMEIDE_BSP_SERVER_BUILDTARGETDEPENDENCYMODULES_DEPENDENCYMODULESRESULT_HPP
#define FLAMEIDE_BSP_SERVER_BUILDTARGETDEPENDENCYMODULES_DEPENDENCYMODULESRESULT_HPP

namespace flame_ide
{namespace bsp
{namespace server
{

class DependencyModulesResult
{};

}}} // flame_ide::bsp::server

#endif // FLAMEIDE_BSP_SERVER_BUILDTARGETDEPENDENCYMODULES_DEPENDENCYMODULESRESULT_HPP
