#ifndef FLAMEIDE_BSP_SERVER_BUILDTARGETDEPENDENCYMODULES_DEPENDENCYMODULEDATA_HPP
#define FLAMEIDE_BSP_SERVER_BUILDTARGETDEPENDENCYMODULES_DEPENDENCYMODULEDATA_HPP

namespace flame_ide
{namespace bsp
{namespace server
{

class DependencyModuleData
{};

}}} // flame_ide::bsp::server

#endif // FLAMEIDE_BSP_SERVER_BUILDTARGETDEPENDENCYMODULES_DEPENDENCYMODULEDATA_HPP
