#ifndef FLAMEIDE_BSP_SERVER_BUILDTARGETDEPENDENCYMODULES_DEPENDENCYMODULESPARAMS_HPP
#define FLAMEIDE_BSP_SERVER_BUILDTARGETDEPENDENCYMODULES_DEPENDENCYMODULESPARAMS_HPP

namespace flame_ide
{namespace bsp
{namespace server
{

class DependencyModulesParams
{};

}}} // flame_ide::bsp::server

#endif // FLAMEIDE_BSP_SERVER_BUILDTARGETDEPENDENCYMODULES_DEPENDENCYMODULESPARAMS_HPP
