#ifndef FLAMEIDE_BSP_SERVER_BUILDTARGETDEPENDENCYMODULES_DEPENDENCYMODULEDATAKIND_HPP
#define FLAMEIDE_BSP_SERVER_BUILDTARGETDEPENDENCYMODULES_DEPENDENCYMODULEDATAKIND_HPP

namespace flame_ide
{namespace bsp
{namespace server
{

class DependencyModuleDataKind
{};

}}} // flame_ide::bsp::server

#endif // FLAMEIDE_BSP_SERVER_BUILDTARGETDEPENDENCYMODULES_DEPENDENCYMODULEDATAKIND_HPP
