#ifndef FLAMEIDE_BSP_SERVER_BUILDTARGETDEPENDENCYMODULES_DEPENDENCYMODULE_HPP
#define FLAMEIDE_BSP_SERVER_BUILDTARGETDEPENDENCYMODULES_DEPENDENCYMODULE_HPP

namespace flame_ide
{namespace bsp
{namespace server
{

class DependencyModule
{};

}}} // flame_ide::bsp::server

#endif // FLAMEIDE_BSP_SERVER_BUILDTARGETDEPENDENCYMODULES_DEPENDENCYMODULE_HPP
