#ifndef FLAMEIDE_BSP_SERVER_BUILDTARGETCOMPILE_COMPILERESULTDATA_HPP
#define FLAMEIDE_BSP_SERVER_BUILDTARGETCOMPILE_COMPILERESULTDATA_HPP

namespace flame_ide
{namespace bsp
{namespace server
{

class CompileResultData
{};

}}} // flame_ide::bsp::server

#endif // FLAMEIDE_BSP_SERVER_BUILDTARGETCOMPILE_COMPILERESULTDATA_HPP
